name: Pipeline CI Examen Inventario

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: uses/setup-node@v3
      with:
        node-version: '20'
    - run: |
        cd frontend
        npm ci
        npm run build